/**
 * AUTO-GENERATED by scripts/generate-trinket-icons.mjs — DO NOT EDIT BY HAND.
 * Regenerate with: node scripts/generate-trinket-icons.mjs
 *
 * Static require() registry of trinket icons under assets/media/Trinkets,
 * keyed by the id-based icon filename (trinket_<id>_icon.png), plus the
 * resolver that maps a trinket from trinkets_rebirth.json to its icon via the
 * trinket's `icon` field. Generated only for trinkets in trinkets_rebirth.json
 * so the bundle stays small.
 */
import { ImageSourcePropType } from 'react-native';

/** Map of icon filename -> bundled module, also used as the known-file set. */
export const trinketIcons: Partial<Record<string, ImageSourcePropType>> = {
  "trinket_10_icon.png": require("../../assets/media/Trinkets/trinket_10_icon.png"),
  "trinket_11_icon.png": require("../../assets/media/Trinkets/trinket_11_icon.png"),
  "trinket_12_icon.png": require("../../assets/media/Trinkets/trinket_12_icon.png"),
  "trinket_13_icon.png": require("../../assets/media/Trinkets/trinket_13_icon.png"),
  "trinket_14_icon.png": require("../../assets/media/Trinkets/trinket_14_icon.png"),
  "trinket_15_icon.png": require("../../assets/media/Trinkets/trinket_15_icon.png"),
  "trinket_16_icon.png": require("../../assets/media/Trinkets/trinket_16_icon.png"),
  "trinket_17_icon.png": require("../../assets/media/Trinkets/trinket_17_icon.png"),
  "trinket_18_icon.png": require("../../assets/media/Trinkets/trinket_18_icon.png"),
  "trinket_19_icon.png": require("../../assets/media/Trinkets/trinket_19_icon.png"),
  "trinket_1_icon.png": require("../../assets/media/Trinkets/trinket_1_icon.png"),
  "trinket_20_icon.png": require("../../assets/media/Trinkets/trinket_20_icon.png"),
  "trinket_21_icon.png": require("../../assets/media/Trinkets/trinket_21_icon.png"),
  "trinket_22_icon.png": require("../../assets/media/Trinkets/trinket_22_icon.png"),
  "trinket_23_icon.png": require("../../assets/media/Trinkets/trinket_23_icon.png"),
  "trinket_24_icon.png": require("../../assets/media/Trinkets/trinket_24_icon.png"),
  "trinket_25_icon.png": require("../../assets/media/Trinkets/trinket_25_icon.png"),
  "trinket_26_icon.png": require("../../assets/media/Trinkets/trinket_26_icon.png"),
  "trinket_27_icon.png": require("../../assets/media/Trinkets/trinket_27_icon.png"),
  "trinket_28_icon.png": require("../../assets/media/Trinkets/trinket_28_icon.png"),
  "trinket_29_icon.png": require("../../assets/media/Trinkets/trinket_29_icon.png"),
  "trinket_2_icon.png": require("../../assets/media/Trinkets/trinket_2_icon.png"),
  "trinket_30_icon.png": require("../../assets/media/Trinkets/trinket_30_icon.png"),
  "trinket_31_icon.png": require("../../assets/media/Trinkets/trinket_31_icon.png"),
  "trinket_32_icon.png": require("../../assets/media/Trinkets/trinket_32_icon.png"),
  "trinket_33_icon.png": require("../../assets/media/Trinkets/trinket_33_icon.png"),
  "trinket_34_icon.png": require("../../assets/media/Trinkets/trinket_34_icon.png"),
  "trinket_35_icon.png": require("../../assets/media/Trinkets/trinket_35_icon.png"),
  "trinket_36_icon.png": require("../../assets/media/Trinkets/trinket_36_icon.png"),
  "trinket_37_icon.png": require("../../assets/media/Trinkets/trinket_37_icon.png"),
  "trinket_38_icon.png": require("../../assets/media/Trinkets/trinket_38_icon.png"),
  "trinket_39_icon.png": require("../../assets/media/Trinkets/trinket_39_icon.png"),
  "trinket_3_icon.png": require("../../assets/media/Trinkets/trinket_3_icon.png"),
  "trinket_40_icon.png": require("../../assets/media/Trinkets/trinket_40_icon.png"),
  "trinket_41_icon.png": require("../../assets/media/Trinkets/trinket_41_icon.png"),
  "trinket_42_icon.png": require("../../assets/media/Trinkets/trinket_42_icon.png"),
  "trinket_43_icon.png": require("../../assets/media/Trinkets/trinket_43_icon.png"),
  "trinket_44_icon.png": require("../../assets/media/Trinkets/trinket_44_icon.png"),
  "trinket_45_icon.png": require("../../assets/media/Trinkets/trinket_45_icon.png"),
  "trinket_46_icon.png": require("../../assets/media/Trinkets/trinket_46_icon.png"),
  "trinket_48_icon.png": require("../../assets/media/Trinkets/trinket_48_icon.png"),
  "trinket_49_icon.png": require("../../assets/media/Trinkets/trinket_49_icon.png"),
  "trinket_4_icon.png": require("../../assets/media/Trinkets/trinket_4_icon.png"),
  "trinket_50_icon.png": require("../../assets/media/Trinkets/trinket_50_icon.png"),
  "trinket_51_icon.png": require("../../assets/media/Trinkets/trinket_51_icon.png"),
  "trinket_52_icon.png": require("../../assets/media/Trinkets/trinket_52_icon.png"),
  "trinket_53_icon.png": require("../../assets/media/Trinkets/trinket_53_icon.png"),
  "trinket_54_icon.png": require("../../assets/media/Trinkets/trinket_54_icon.png"),
  "trinket_55_icon.png": require("../../assets/media/Trinkets/trinket_55_icon.png"),
  "trinket_56_icon.png": require("../../assets/media/Trinkets/trinket_56_icon.png"),
  "trinket_58_icon.png": require("../../assets/media/Trinkets/trinket_58_icon.png"),
  "trinket_59_icon.png": require("../../assets/media/Trinkets/trinket_59_icon.png"),
  "trinket_5_icon.png": require("../../assets/media/Trinkets/trinket_5_icon.png"),
  "trinket_60_icon.png": require("../../assets/media/Trinkets/trinket_60_icon.png"),
  "trinket_61_icon.png": require("../../assets/media/Trinkets/trinket_61_icon.png"),
  "trinket_6_icon.png": require("../../assets/media/Trinkets/trinket_6_icon.png"),
  "trinket_7_icon.png": require("../../assets/media/Trinkets/trinket_7_icon.png"),
  "trinket_8_icon.png": require("../../assets/media/Trinkets/trinket_8_icon.png"),
  "trinket_9_icon.png": require("../../assets/media/Trinkets/trinket_9_icon.png"),
};

const KNOWN = new Set(Object.keys(trinketIcons));

/** Resolve the icon filename for a trinket (or null if no icon exists). */
export function iconFilenameForTrinket(trinket: { icon?: string }): string | null {
  if (trinket && typeof trinket.icon === 'string' && KNOWN.has(trinket.icon)) return trinket.icon;
  return null;
}
